#!/bin/bash


BLUE='\033[1;34m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

for arg in "$@"
do
    if [ "$arg" == "--no-deps" ]; then
            no_deps=true
    fi

    if [ "$arg" == "--no-ds" ]; then
	    no_ds=true
    fi
done


if [ ! "$no_deps" ]; then
    echo -e "${YELLOW}Installing dependencies${NC}"
    ./dependencies
fi

if [ ! "$no_ds" ]; then
    echo -e "${BLUE}Downloading dataset${NC}"
    python3 ./DATASETS/get_dataset.py
fi


echo -e "${GREEN}Started training process${NC}"
CUDA_VISIBLE_DEVICES=2,5,6 python3 ./train.py

