#!/bin/bash

BLUE='\033[1;34m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

for arg in "$@"
do
    if [ "$arg" == "--no-deps" ]; then
        no_deps=true
    fi
done


if [ ! "$no_deps" ]; then
    echo -e "${YELLOW}Installing dependencies${NC}"
    ./dependencies
fi

CUDA_VISIBLE_DEVICES=5 python3 ./test.py

